language: go

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

install: true

matrix:
  include:
    - go: "1.10.x"
      script: goveralls -v -service travis-ci -repotoken $COVERALLS_TOKEN || go test -v ./...
    - go: "1.11.x"
      script: goveralls -v -service travis-ci -repotoken $COVERALLS_TOKEN || go test -v -mod=vendor ./...
